import 'dotenv/config';
import postgres from 'postgres';

const DATABASE_URL =
  process.env['DATABASE_URL'] ?? 'postgresql://postgres:postgres@localhost:5432/openpulse';

interface ServiceSeed {
  name: string;
  slug: string;
  url: string;
  description: string;
  statusPageUrl: string | null;
}

interface CategorySeed {
  name: string;
  slug: string;
  icon: string;
  services: ServiceSeed[];
}

const categories: CategorySeed[] = [
  {
    name: 'Cloud',
    slug: 'cloud',
    icon: 'cloud',
    services: [
      { name: 'AWS', slug: 'aws', url: 'https://aws.amazon.com', description: 'Amazon Web Services cloud computing platform', statusPageUrl: 'https://health.aws.amazon.com' },
      { name: 'Google Cloud Platform', slug: 'google-cloud-platform', url: 'https://cloud.google.com', description: 'Google suite of cloud computing services', statusPageUrl: 'https://status.cloud.google.com' },
      { name: 'Microsoft Azure', slug: 'microsoft-azure', url: 'https://azure.microsoft.com', description: 'Microsoft cloud computing platform and services', statusPageUrl: 'https://status.azure.com' },
      { name: 'Cloudflare', slug: 'cloudflare', url: 'https://www.cloudflare.com', description: 'Web performance and security company', statusPageUrl: 'https://www.cloudflarestatus.com' },
      { name: 'Vercel', slug: 'vercel', url: 'https://vercel.com', description: 'Frontend cloud platform for deploying web applications', statusPageUrl: 'https://www.vercel-status.com' },
      { name: 'Netlify', slug: 'netlify', url: 'https://www.netlify.com', description: 'Platform for deploying modern web projects', statusPageUrl: 'https://www.netlifystatus.com' },
      { name: 'DigitalOcean', slug: 'digitalocean', url: 'https://www.digitalocean.com', description: 'Cloud infrastructure provider for developers', statusPageUrl: 'https://status.digitalocean.com' },
      { name: 'Heroku', slug: 'heroku', url: 'https://www.heroku.com', description: 'Cloud platform as a service for app deployment', statusPageUrl: 'https://status.heroku.com' },
      { name: 'Fly.io', slug: 'fly-io', url: 'https://fly.io', description: 'Platform for running full-stack apps globally', statusPageUrl: 'https://status.flyio.net' },
      { name: 'Railway', slug: 'railway', url: 'https://railway.app', description: 'Infrastructure platform for deploying apps', statusPageUrl: 'https://status.railway.app' },
      { name: 'Render', slug: 'render', url: 'https://render.com', description: 'Unified cloud platform to build and run apps', statusPageUrl: 'https://status.render.com' },
      { name: 'Supabase', slug: 'supabase', url: 'https://supabase.com', description: 'Open source Firebase alternative with Postgres', statusPageUrl: 'https://status.supabase.com' },
      { name: 'PlanetScale', slug: 'planetscale', url: 'https://planetscale.com', description: 'Serverless MySQL database platform', statusPageUrl: 'https://www.planetscalestatus.com' },
      { name: 'Neon', slug: 'neon', url: 'https://neon.tech', description: 'Serverless Postgres database with branching', statusPageUrl: 'https://neonstatus.com' },
      { name: 'Upstash', slug: 'upstash', url: 'https://upstash.com', description: 'Serverless Redis and Kafka provider', statusPageUrl: 'https://status.upstash.com' },
      { name: 'MongoDB Atlas', slug: 'mongodb-atlas', url: 'https://www.mongodb.com/atlas', description: 'Fully managed cloud MongoDB service', statusPageUrl: 'https://status.cloud.mongodb.com' },
      { name: 'Elastic Cloud', slug: 'elastic-cloud', url: 'https://www.elastic.co/cloud', description: 'Managed Elasticsearch and Kibana service', statusPageUrl: 'https://cloud-status.elastic.co' },
      { name: 'Datadog', slug: 'datadog', url: 'https://www.datadoghq.com', description: 'Cloud monitoring and security platform', statusPageUrl: 'https://status.datadoghq.com' },
      { name: 'New Relic', slug: 'new-relic', url: 'https://newrelic.com', description: 'Full-stack observability platform', statusPageUrl: 'https://status.newrelic.com' },
      { name: 'Grafana Cloud', slug: 'grafana-cloud', url: 'https://grafana.com/products/cloud', description: 'Managed observability platform', statusPageUrl: 'https://status.grafana.com' },
      { name: 'Akamai', slug: 'akamai', url: 'https://www.akamai.com', description: 'Content delivery network and cloud security', statusPageUrl: 'https://www.akamaistatus.com' },
      { name: 'Fastly', slug: 'fastly', url: 'https://www.fastly.com', description: 'Edge cloud platform and CDN provider', statusPageUrl: 'https://status.fastly.com' },
      { name: 'Oracle Cloud', slug: 'oracle-cloud', url: 'https://www.oracle.com/cloud', description: 'Oracle cloud infrastructure and applications', statusPageUrl: 'https://ocistatus.oraclecloud.com' },
      { name: 'IBM Cloud', slug: 'ibm-cloud', url: 'https://www.ibm.com/cloud', description: 'IBM enterprise cloud computing platform', statusPageUrl: 'https://cloud.ibm.com/status' },
      { name: 'Alibaba Cloud', slug: 'alibaba-cloud', url: 'https://www.alibabacloud.com', description: 'Alibaba Group cloud computing arm', statusPageUrl: 'https://status.alibabacloud.com' },
      { name: 'Linode', slug: 'linode', url: 'https://www.linode.com', description: 'Cloud hosting and Linux virtual machines', statusPageUrl: 'https://status.linode.com' },
      { name: 'Vultr', slug: 'vultr', url: 'https://www.vultr.com', description: 'SSD cloud servers and bare metal', statusPageUrl: 'https://www.vultr.com/status' },
      { name: 'Hetzner', slug: 'hetzner', url: 'https://www.hetzner.com', description: 'European cloud hosting and dedicated servers', statusPageUrl: 'https://status.hetzner.com' },
      { name: 'OVHcloud', slug: 'ovhcloud', url: 'https://www.ovhcloud.com', description: 'European cloud provider and hosting', statusPageUrl: 'https://www.status-ovhcloud.com' },
      { name: 'Scaleway', slug: 'scaleway', url: 'https://www.scaleway.com', description: 'European multi-cloud and edge computing', statusPageUrl: 'https://status.scaleway.com' },
      { name: 'Wasabi', slug: 'wasabi', url: 'https://wasabi.com', description: 'Hot cloud storage provider', statusPageUrl: 'https://status.wasabi.com' },
      { name: 'Backblaze', slug: 'backblaze', url: 'https://www.backblaze.com', description: 'Cloud backup and B2 cloud storage', statusPageUrl: 'https://status.backblaze.com' },
      { name: 'CloudAMQP', slug: 'cloudamqp', url: 'https://www.cloudamqp.com', description: 'Managed RabbitMQ servers in the cloud', statusPageUrl: 'https://status.cloudamqp.com' },
      { name: 'Redis Cloud', slug: 'redis-cloud', url: 'https://redis.com/cloud', description: 'Fully managed Redis enterprise service', statusPageUrl: 'https://status.redis.io' },
      { name: 'CockroachDB Cloud', slug: 'cockroachdb-cloud', url: 'https://www.cockroachlabs.com', description: 'Distributed SQL database as a service', statusPageUrl: 'https://status.cockroachlabs.cloud' },
      { name: 'Confluent Cloud', slug: 'confluent-cloud', url: 'https://www.confluent.io', description: 'Fully managed Apache Kafka service', statusPageUrl: 'https://status.confluent.cloud' },
      { name: 'Snowflake', slug: 'snowflake', url: 'https://www.snowflake.com', description: 'Cloud data warehousing platform', statusPageUrl: 'https://status.snowflake.com' },
      { name: 'Databricks', slug: 'databricks', url: 'https://www.databricks.com', description: 'Unified analytics and AI platform', statusPageUrl: 'https://status.databricks.com' },
      { name: 'Terraform Cloud', slug: 'terraform-cloud', url: 'https://app.terraform.io', description: 'HashiCorp infrastructure as code platform', statusPageUrl: 'https://status.hashicorp.com' },
      { name: 'Pulumi', slug: 'pulumi', url: 'https://www.pulumi.com', description: 'Infrastructure as code in any programming language', statusPageUrl: 'https://status.pulumi.com' },
      { name: 'Deno Deploy', slug: 'deno-deploy', url: 'https://deno.com/deploy', description: 'Serverless JavaScript/TypeScript edge runtime', statusPageUrl: 'https://www.denostatus.com' },
      { name: 'Workers (Cloudflare)', slug: 'cloudflare-workers', url: 'https://workers.cloudflare.com', description: 'Serverless execution environment on Cloudflare edge', statusPageUrl: 'https://www.cloudflarestatus.com' },
      { name: 'Lambda (AWS)', slug: 'aws-lambda', url: 'https://aws.amazon.com/lambda', description: 'AWS serverless compute service', statusPageUrl: 'https://health.aws.amazon.com' },
      { name: 'Cloud Functions (GCP)', slug: 'gcp-cloud-functions', url: 'https://cloud.google.com/functions', description: 'Google Cloud serverless functions', statusPageUrl: 'https://status.cloud.google.com' },
      { name: 'Azure Functions', slug: 'azure-functions', url: 'https://azure.microsoft.com/en-us/products/functions', description: 'Microsoft serverless compute service', statusPageUrl: 'https://status.azure.com' },
      { name: 'Sentry', slug: 'sentry', url: 'https://sentry.io', description: 'Application performance monitoring and error tracking', statusPageUrl: 'https://status.sentry.io' },
      { name: 'LaunchDarkly', slug: 'launchdarkly', url: 'https://launchdarkly.com', description: 'Feature flag management platform', statusPageUrl: 'https://status.launchdarkly.com' },
      { name: 'PagerDuty', slug: 'pagerduty', url: 'https://www.pagerduty.com', description: 'Incident management and on-call scheduling', statusPageUrl: 'https://status.pagerduty.com' },
      { name: 'Twilio', slug: 'twilio', url: 'https://www.twilio.com', description: 'Cloud communications platform', statusPageUrl: 'https://status.twilio.com' },
      { name: 'SendGrid', slug: 'sendgrid', url: 'https://sendgrid.com', description: 'Cloud-based email delivery service', statusPageUrl: 'https://status.sendgrid.com' },
    ],
  },
  {
    name: 'Social',
    slug: 'social',
    icon: 'users',
    services: [
      { name: 'Twitter / X', slug: 'twitter-x', url: 'https://x.com', description: 'Microblogging and social networking platform', statusPageUrl: 'https://api.twitterstat.us' },
      { name: 'Facebook', slug: 'facebook', url: 'https://www.facebook.com', description: 'Social networking service by Meta', statusPageUrl: null },
      { name: 'Instagram', slug: 'instagram', url: 'https://www.instagram.com', description: 'Photo and video sharing social network', statusPageUrl: null },
      { name: 'TikTok', slug: 'tiktok', url: 'https://www.tiktok.com', description: 'Short-form video hosting service', statusPageUrl: null },
      { name: 'Reddit', slug: 'reddit', url: 'https://www.reddit.com', description: 'Social news aggregation and discussion', statusPageUrl: 'https://www.redditstatus.com' },
      { name: 'LinkedIn', slug: 'linkedin', url: 'https://www.linkedin.com', description: 'Professional networking platform', statusPageUrl: null },
      { name: 'Mastodon', slug: 'mastodon', url: 'https://mastodon.social', description: 'Decentralized social networking platform', statusPageUrl: null },
      { name: 'Bluesky', slug: 'bluesky', url: 'https://bsky.app', description: 'Decentralized social media protocol and app', statusPageUrl: 'https://status.bsky.app' },
      { name: 'Threads', slug: 'threads', url: 'https://www.threads.net', description: 'Text-based social network by Meta', statusPageUrl: null },
      { name: 'Pinterest', slug: 'pinterest', url: 'https://www.pinterest.com', description: 'Visual discovery and bookmarking platform', statusPageUrl: null },
      { name: 'Snapchat', slug: 'snapchat', url: 'https://www.snapchat.com', description: 'Multimedia instant messaging app', statusPageUrl: null },
      { name: 'Discord', slug: 'discord', url: 'https://discord.com', description: 'Voice, video, and text communication platform', statusPageUrl: 'https://discordstatus.com' },
      { name: 'WhatsApp', slug: 'whatsapp', url: 'https://www.whatsapp.com', description: 'Cross-platform messaging and VoIP service', statusPageUrl: null },
      { name: 'Telegram', slug: 'telegram', url: 'https://telegram.org', description: 'Cloud-based messaging and VoIP service', statusPageUrl: null },
      { name: 'Signal', slug: 'signal', url: 'https://signal.org', description: 'Encrypted messaging and calling app', statusPageUrl: null },
      { name: 'Tumblr', slug: 'tumblr', url: 'https://www.tumblr.com', description: 'Microblogging and social networking website', statusPageUrl: null },
      { name: 'Quora', slug: 'quora', url: 'https://www.quora.com', description: 'Question-and-answer social platform', statusPageUrl: null },
      { name: 'Clubhouse', slug: 'clubhouse', url: 'https://www.clubhouse.com', description: 'Social audio app for drop-in conversations', statusPageUrl: null },
      { name: 'BeReal', slug: 'bereal', url: 'https://bereal.com', description: 'Photo sharing app with spontaneous posting', statusPageUrl: null },
      { name: 'Nextdoor', slug: 'nextdoor', url: 'https://nextdoor.com', description: 'Neighborhood-based social networking', statusPageUrl: null },
      { name: 'Twitch Chat', slug: 'twitch-chat', url: 'https://www.twitch.tv', description: 'Live streaming platform chat system', statusPageUrl: 'https://status.twitch.tv' },
      { name: 'Kick', slug: 'kick', url: 'https://kick.com', description: 'Live streaming platform', statusPageUrl: null },
      { name: 'VK', slug: 'vk', url: 'https://vk.com', description: 'Russian social networking service', statusPageUrl: null },
      { name: 'Weibo', slug: 'weibo', url: 'https://weibo.com', description: 'Chinese microblogging platform', statusPageUrl: null },
      { name: 'LINE', slug: 'line', url: 'https://line.me', description: 'Japanese messaging and social platform', statusPageUrl: null },
      { name: 'KakaoTalk', slug: 'kakaotalk', url: 'https://www.kakaocorp.com/page/service/service/KakaoTalk', description: 'South Korean mobile messaging app', statusPageUrl: null },
      { name: 'Viber', slug: 'viber', url: 'https://www.viber.com', description: 'Cross-platform VoIP and messaging app', statusPageUrl: null },
      { name: 'WeChat', slug: 'wechat', url: 'https://www.wechat.com', description: 'Chinese multi-purpose messaging and social app', statusPageUrl: null },
      { name: 'Lemon8', slug: 'lemon8', url: 'https://www.lemon8-app.com', description: 'Lifestyle community platform by ByteDance', statusPageUrl: null },
      { name: 'Hive Social', slug: 'hive-social', url: 'https://www.hivesocial.app', description: 'Social media platform with chronological feeds', statusPageUrl: null },
      { name: 'Gab', slug: 'gab', url: 'https://gab.com', description: 'Free speech social networking platform', statusPageUrl: null },
      { name: 'Truth Social', slug: 'truth-social', url: 'https://truthsocial.com', description: 'Social media platform by Trump Media', statusPageUrl: null },
      { name: 'Parler', slug: 'parler', url: 'https://parler.com', description: 'Microblogging and social networking service', statusPageUrl: null },
      { name: 'Rumble', slug: 'rumble', url: 'https://rumble.com', description: 'Video hosting platform', statusPageUrl: null },
      { name: 'Minds', slug: 'minds', url: 'https://www.minds.com', description: 'Open-source social networking service', statusPageUrl: null },
      { name: 'Pixelfed', slug: 'pixelfed', url: 'https://pixelfed.org', description: 'Decentralized photo sharing platform', statusPageUrl: null },
      { name: 'Lemmy', slug: 'lemmy', url: 'https://join-lemmy.org', description: 'Federated link aggregator and forum', statusPageUrl: null },
      { name: 'Misskey', slug: 'misskey', url: 'https://misskey-hub.net', description: 'Decentralized social microblogging platform', statusPageUrl: null },
      { name: 'Cohost', slug: 'cohost', url: 'https://cohost.org', description: 'Social media platform focused on posting', statusPageUrl: null },
      { name: 'Diaspora', slug: 'diaspora', url: 'https://diasporafoundation.org', description: 'Decentralized social networking service', statusPageUrl: null },
    ],
  },
  {
    name: 'Gaming',
    slug: 'gaming',
    icon: 'gamepad',
    services: [
      { name: 'Steam', slug: 'steam', url: 'https://store.steampowered.com', description: 'Digital distribution platform for video games', statusPageUrl: 'https://steamstat.us' },
      { name: 'Xbox Live', slug: 'xbox-live', url: 'https://www.xbox.com', description: 'Microsoft online gaming and digital media service', statusPageUrl: 'https://support.xbox.com/en-US/xbox-live-status' },
      { name: 'PlayStation Network', slug: 'playstation-network', url: 'https://www.playstation.com', description: 'Sony digital entertainment service', statusPageUrl: 'https://status.playstation.com' },
      { name: 'Epic Games Store', slug: 'epic-games-store', url: 'https://store.epicgames.com', description: 'Digital video game storefront by Epic Games', statusPageUrl: 'https://status.epicgames.com' },
      { name: 'Riot Games', slug: 'riot-games', url: 'https://www.riotgames.com', description: 'Video game developer and publisher', statusPageUrl: 'https://status.riotgames.com' },
      { name: 'Blizzard Battle.net', slug: 'blizzard-battlenet', url: 'https://www.blizzard.com', description: 'Blizzard online gaming platform', statusPageUrl: null },
      { name: 'EA', slug: 'ea', url: 'https://www.ea.com', description: 'Electronic Arts gaming services', statusPageUrl: 'https://www.ea.com/able/service-updates' },
      { name: 'Ubisoft Connect', slug: 'ubisoft-connect', url: 'https://www.ubisoft.com', description: 'Ubisoft gaming platform and store', statusPageUrl: null },
      { name: 'Nintendo Online', slug: 'nintendo-online', url: 'https://www.nintendo.com', description: 'Nintendo online gaming subscription service', statusPageUrl: null },
      { name: 'Roblox', slug: 'roblox', url: 'https://www.roblox.com', description: 'Online game platform and game creation system', statusPageUrl: 'https://status.roblox.com' },
      { name: 'Minecraft', slug: 'minecraft', url: 'https://www.minecraft.net', description: 'Sandbox video game by Mojang Studios', statusPageUrl: null },
      { name: 'Fortnite', slug: 'fortnite', url: 'https://www.fortnite.com', description: 'Online battle royale game by Epic Games', statusPageUrl: 'https://status.epicgames.com' },
      { name: 'Valorant', slug: 'valorant', url: 'https://playvalorant.com', description: 'Free-to-play tactical shooter by Riot Games', statusPageUrl: 'https://status.riotgames.com' },
      { name: 'League of Legends', slug: 'league-of-legends', url: 'https://www.leagueoflegends.com', description: 'Multiplayer online battle arena game', statusPageUrl: 'https://status.riotgames.com' },
      { name: 'Apex Legends', slug: 'apex-legends', url: 'https://www.ea.com/games/apex-legends', description: 'Free-to-play battle royale hero shooter', statusPageUrl: null },
      { name: 'Call of Duty', slug: 'call-of-duty', url: 'https://www.callofduty.com', description: 'First-person shooter franchise by Activision', statusPageUrl: null },
      { name: 'Destiny 2', slug: 'destiny-2', url: 'https://www.bungie.net/7/en/Destiny', description: 'Free-to-play online multiplayer FPS', statusPageUrl: 'https://help.bungie.net' },
      { name: 'Genshin Impact', slug: 'genshin-impact', url: 'https://genshin.hoyoverse.com', description: 'Open-world action RPG by miHoYo', statusPageUrl: null },
      { name: 'World of Warcraft', slug: 'world-of-warcraft', url: 'https://worldofwarcraft.blizzard.com', description: 'Massively multiplayer online role-playing game', statusPageUrl: null },
      { name: 'Final Fantasy XIV', slug: 'final-fantasy-xiv', url: 'https://www.finalfantasyxiv.com', description: 'MMORPG by Square Enix', statusPageUrl: null },
      { name: 'Diablo IV', slug: 'diablo-iv', url: 'https://diablo4.blizzard.com', description: 'Action RPG by Blizzard Entertainment', statusPageUrl: null },
      { name: 'Counter-Strike 2', slug: 'counter-strike-2', url: 'https://www.counter-strike.net', description: 'Competitive first-person shooter by Valve', statusPageUrl: null },
      { name: 'Dota 2', slug: 'dota-2', url: 'https://www.dota2.com', description: 'Multiplayer online battle arena by Valve', statusPageUrl: null },
      { name: 'Overwatch 2', slug: 'overwatch-2', url: 'https://overwatch.blizzard.com', description: 'Team-based action game by Blizzard', statusPageUrl: null },
      { name: 'GOG Galaxy', slug: 'gog-galaxy', url: 'https://www.gog.com', description: 'DRM-free digital distribution platform', statusPageUrl: null },
      { name: 'Humble Bundle', slug: 'humble-bundle', url: 'https://www.humblebundle.com', description: 'Digital storefront for games and bundles', statusPageUrl: null },
      { name: 'NVIDIA GeForce NOW', slug: 'nvidia-geforce-now', url: 'https://www.nvidia.com/en-us/geforce-now', description: 'Cloud gaming streaming service', statusPageUrl: 'https://status.geforcenow.com' },
      { name: 'Xbox Cloud Gaming', slug: 'xbox-cloud-gaming', url: 'https://www.xbox.com/en-US/play', description: 'Microsoft cloud gaming service', statusPageUrl: null },
      { name: 'PlayStation Now', slug: 'playstation-now', url: 'https://www.playstation.com/en-us/ps-now', description: 'Sony cloud gaming streaming service', statusPageUrl: null },
      { name: 'Twitch', slug: 'twitch', url: 'https://www.twitch.tv', description: 'Live streaming platform for gamers', statusPageUrl: 'https://status.twitch.tv' },
      { name: 'Steam Deck', slug: 'steam-deck', url: 'https://store.steampowered.com/steamdeck', description: 'Valve handheld gaming computer services', statusPageUrl: null },
      { name: 'itch.io', slug: 'itch-io', url: 'https://itch.io', description: 'Indie game hosting and marketplace', statusPageUrl: null },
      { name: 'Garena', slug: 'garena', url: 'https://www.garena.com', description: 'Southeast Asian gaming platform', statusPageUrl: null },
      { name: 'Bethesda.net', slug: 'bethesda-net', url: 'https://bethesda.net', description: 'Bethesda Softworks game platform', statusPageUrl: null },
      { name: 'Square Enix', slug: 'square-enix', url: 'https://www.square-enix.com', description: 'Japanese video game publisher services', statusPageUrl: null },
      { name: 'Rockstar Games', slug: 'rockstar-games', url: 'https://www.rockstargames.com', description: 'Rockstar Games Social Club and services', statusPageUrl: null },
      { name: 'GTA Online', slug: 'gta-online', url: 'https://www.rockstargames.com/gta-online', description: 'Grand Theft Auto multiplayer online', statusPageUrl: null },
      { name: 'Path of Exile', slug: 'path-of-exile', url: 'https://www.pathofexile.com', description: 'Free-to-play action RPG by Grinding Gear Games', statusPageUrl: null },
      { name: 'Warframe', slug: 'warframe', url: 'https://www.warframe.com', description: 'Free-to-play cooperative action game', statusPageUrl: null },
      { name: 'Lost Ark', slug: 'lost-ark', url: 'https://www.playlostark.com', description: 'Free-to-play MMORPG by Smilegate', statusPageUrl: null },
      { name: 'Palworld', slug: 'palworld', url: 'https://www.pocketpair.jp/palworld', description: 'Open-world survival crafting game', statusPageUrl: null },
      { name: 'Helldivers 2', slug: 'helldivers-2', url: 'https://www.playstation.com/en-us/games/helldivers-2', description: 'Cooperative third-person shooter', statusPageUrl: null },
      { name: 'New World', slug: 'new-world', url: 'https://www.newworld.com', description: 'MMO by Amazon Games', statusPageUrl: null },
      { name: 'Star Citizen', slug: 'star-citizen', url: 'https://robertsspaceindustries.com', description: 'Multiplayer space trading and combat game', statusPageUrl: null },
      { name: 'Escape from Tarkov', slug: 'escape-from-tarkov', url: 'https://www.escapefromtarkov.com', description: 'Hardcore FPS survival game', statusPageUrl: null },
      { name: 'Dead by Daylight', slug: 'dead-by-daylight', url: 'https://deadbydaylight.com', description: 'Asymmetric multiplayer horror game', statusPageUrl: null },
      { name: 'Rocket League', slug: 'rocket-league', url: 'https://www.rocketleague.com', description: 'Vehicular soccer video game', statusPageUrl: null },
      { name: 'Fall Guys', slug: 'fall-guys', url: 'https://www.fallguys.com', description: 'Free-to-play party battle royale', statusPageUrl: null },
      { name: 'Among Us', slug: 'among-us', url: 'https://www.innersloth.com/games/among-us', description: 'Online multiplayer social deduction game', statusPageUrl: null },
      { name: 'Sea of Thieves', slug: 'sea-of-thieves', url: 'https://www.seaofthieves.com', description: 'Shared-world pirate adventure game', statusPageUrl: null },
    ],
  },
  {
    name: 'Streaming',
    slug: 'streaming',
    icon: 'play-circle',
    services: [
      { name: 'Netflix', slug: 'netflix', url: 'https://www.netflix.com', description: 'Subscription-based streaming service', statusPageUrl: null },
      { name: 'YouTube', slug: 'youtube', url: 'https://www.youtube.com', description: 'Online video sharing and streaming platform', statusPageUrl: null },
      { name: 'Spotify', slug: 'spotify', url: 'https://www.spotify.com', description: 'Audio streaming and media services', statusPageUrl: null },
      { name: 'Disney+', slug: 'disney-plus', url: 'https://www.disneyplus.com', description: 'Disney subscription streaming service', statusPageUrl: null },
      { name: 'Hulu', slug: 'hulu', url: 'https://www.hulu.com', description: 'Subscription video on demand service', statusPageUrl: null },
      { name: 'HBO Max', slug: 'hbo-max', url: 'https://www.max.com', description: 'Streaming platform from Warner Bros. Discovery', statusPageUrl: null },
      { name: 'Apple TV+', slug: 'apple-tv-plus', url: 'https://tv.apple.com', description: 'Apple subscription streaming service', statusPageUrl: 'https://www.apple.com/support/systemstatus' },
      { name: 'Amazon Prime Video', slug: 'amazon-prime-video', url: 'https://www.primevideo.com', description: 'Amazon subscription streaming service', statusPageUrl: null },
      { name: 'Peacock', slug: 'peacock', url: 'https://www.peacocktv.com', description: 'NBCUniversal streaming service', statusPageUrl: null },
      { name: 'Paramount+', slug: 'paramount-plus', url: 'https://www.paramountplus.com', description: 'ViacomCBS subscription streaming service', statusPageUrl: null },
      { name: 'Crunchyroll', slug: 'crunchyroll', url: 'https://www.crunchyroll.com', description: 'Anime streaming platform', statusPageUrl: null },
      { name: 'SoundCloud', slug: 'soundcloud', url: 'https://soundcloud.com', description: 'Online audio distribution and music sharing', statusPageUrl: 'https://status.soundcloud.com' },
      { name: 'Apple Music', slug: 'apple-music', url: 'https://music.apple.com', description: 'Apple music streaming service', statusPageUrl: 'https://www.apple.com/support/systemstatus' },
      { name: 'Tidal', slug: 'tidal', url: 'https://tidal.com', description: 'High-fidelity music streaming service', statusPageUrl: null },
      { name: 'YouTube Music', slug: 'youtube-music', url: 'https://music.youtube.com', description: 'Google music streaming service', statusPageUrl: null },
      { name: 'Deezer', slug: 'deezer', url: 'https://www.deezer.com', description: 'French music streaming service', statusPageUrl: null },
      { name: 'Amazon Music', slug: 'amazon-music', url: 'https://music.amazon.com', description: 'Amazon music streaming platform', statusPageUrl: null },
      { name: 'Pandora', slug: 'pandora', url: 'https://www.pandora.com', description: 'Music streaming and automated recommendation', statusPageUrl: null },
      { name: 'iHeartRadio', slug: 'iheartradio', url: 'https://www.iheart.com', description: 'Free music streaming and internet radio', statusPageUrl: null },
      { name: 'Roku', slug: 'roku', url: 'https://www.roku.com', description: 'Streaming media player platform', statusPageUrl: null },
      { name: 'Plex', slug: 'plex', url: 'https://www.plex.tv', description: 'Media server and streaming platform', statusPageUrl: 'https://status.plex.tv' },
      { name: 'Vimeo', slug: 'vimeo', url: 'https://vimeo.com', description: 'Video hosting and streaming platform', statusPageUrl: null },
      { name: 'Twitch Streaming', slug: 'twitch-streaming', url: 'https://www.twitch.tv', description: 'Live streaming broadcast infrastructure', statusPageUrl: 'https://status.twitch.tv' },
      { name: 'YouTube TV', slug: 'youtube-tv', url: 'https://tv.youtube.com', description: 'Google live TV streaming service', statusPageUrl: null },
      { name: 'Sling TV', slug: 'sling-tv', url: 'https://www.sling.com', description: 'Over-the-top internet television', statusPageUrl: null },
      { name: 'fuboTV', slug: 'fubotv', url: 'https://www.fubo.tv', description: 'Sports-focused live TV streaming', statusPageUrl: null },
      { name: 'Philo', slug: 'philo', url: 'https://www.philo.com', description: 'Budget live TV streaming service', statusPageUrl: null },
      { name: 'Discovery+', slug: 'discovery-plus', url: 'https://www.discoveryplus.com', description: 'Discovery channel streaming service', statusPageUrl: null },
      { name: 'ESPN+', slug: 'espn-plus', url: 'https://plus.espn.com', description: 'Sports streaming by ESPN', statusPageUrl: null },
      { name: 'DAZN', slug: 'dazn', url: 'https://www.dazn.com', description: 'Sports streaming subscription service', statusPageUrl: null },
      { name: 'Funimation', slug: 'funimation', url: 'https://www.funimation.com', description: 'Anime streaming and distribution', statusPageUrl: null },
      { name: 'BritBox', slug: 'britbox', url: 'https://www.britbox.com', description: 'British TV streaming service', statusPageUrl: null },
      { name: 'Curiosity Stream', slug: 'curiosity-stream', url: 'https://curiositystream.com', description: 'Documentary streaming service', statusPageUrl: null },
      { name: 'Shudder', slug: 'shudder', url: 'https://www.shudder.com', description: 'Horror and thriller streaming service', statusPageUrl: null },
      { name: 'Mubi', slug: 'mubi', url: 'https://mubi.com', description: 'Curated cinema streaming platform', statusPageUrl: null },
      { name: 'Nebula', slug: 'nebula', url: 'https://nebula.tv', description: 'Creator-owned streaming service', statusPageUrl: null },
      { name: 'Audible', slug: 'audible', url: 'https://www.audible.com', description: 'Audiobook and podcast streaming service', statusPageUrl: null },
      { name: 'Podcasts (Apple)', slug: 'apple-podcasts', url: 'https://podcasts.apple.com', description: 'Apple podcast streaming service', statusPageUrl: null },
      { name: 'Spotify Podcasts', slug: 'spotify-podcasts', url: 'https://podcasters.spotify.com', description: 'Spotify podcast distribution platform', statusPageUrl: null },
      { name: 'Dailymotion', slug: 'dailymotion', url: 'https://www.dailymotion.com', description: 'French video-sharing technology platform', statusPageUrl: null },
    ],
  },
  {
    name: 'Banking',
    slug: 'banking',
    icon: 'dollar-sign',
    services: [
      { name: 'Chase', slug: 'chase', url: 'https://www.chase.com', description: 'JPMorgan Chase consumer and commercial banking', statusPageUrl: null },
      { name: 'Bank of America', slug: 'bank-of-america', url: 'https://www.bankofamerica.com', description: 'Consumer banking and financial services', statusPageUrl: null },
      { name: 'Wells Fargo', slug: 'wells-fargo', url: 'https://www.wellsfargo.com', description: 'Multinational financial services company', statusPageUrl: null },
      { name: 'Citibank', slug: 'citibank', url: 'https://www.citi.com', description: 'Consumer division of Citigroup', statusPageUrl: null },
      { name: 'Capital One', slug: 'capital-one', url: 'https://www.capitalone.com', description: 'Bank holding company and financial services', statusPageUrl: null },
      { name: 'Stripe', slug: 'stripe', url: 'https://stripe.com', description: 'Online payment processing platform', statusPageUrl: 'https://status.stripe.com' },
      { name: 'PayPal', slug: 'paypal', url: 'https://www.paypal.com', description: 'Online payments and money transfers', statusPageUrl: null },
      { name: 'Square', slug: 'square', url: 'https://squareup.com', description: 'Financial services and digital payments', statusPageUrl: 'https://www.issquareup.com' },
      { name: 'Venmo', slug: 'venmo', url: 'https://venmo.com', description: 'Mobile payment service by PayPal', statusPageUrl: null },
      { name: 'Zelle', slug: 'zelle', url: 'https://www.zellepay.com', description: 'Digital payments network for US banks', statusPageUrl: null },
      { name: 'Robinhood', slug: 'robinhood', url: 'https://robinhood.com', description: 'Commission-free stock trading platform', statusPageUrl: 'https://status.robinhood.com' },
      { name: 'Coinbase', slug: 'coinbase', url: 'https://www.coinbase.com', description: 'Cryptocurrency exchange platform', statusPageUrl: 'https://status.coinbase.com' },
      { name: 'Binance', slug: 'binance', url: 'https://www.binance.com', description: 'Global cryptocurrency exchange', statusPageUrl: null },
      { name: 'Kraken', slug: 'kraken', url: 'https://www.kraken.com', description: 'US-based cryptocurrency exchange', statusPageUrl: 'https://status.kraken.com' },
      { name: 'Plaid', slug: 'plaid', url: 'https://plaid.com', description: 'Financial data connectivity platform', statusPageUrl: 'https://status.plaid.com' },
      { name: 'Wise', slug: 'wise', url: 'https://wise.com', description: 'International money transfer service', statusPageUrl: null },
      { name: 'Revolut', slug: 'revolut', url: 'https://www.revolut.com', description: 'Digital banking and financial super app', statusPageUrl: null },
      { name: 'Chime', slug: 'chime', url: 'https://www.chime.com', description: 'Mobile-first financial technology company', statusPageUrl: null },
      { name: 'Cash App', slug: 'cash-app', url: 'https://cash.app', description: 'Mobile payment service by Block Inc', statusPageUrl: null },
      { name: 'Affirm', slug: 'affirm', url: 'https://www.affirm.com', description: 'Buy-now-pay-later financial technology', statusPageUrl: null },
      { name: 'Klarna', slug: 'klarna', url: 'https://www.klarna.com', description: 'Swedish buy-now-pay-later fintech', statusPageUrl: null },
      { name: 'Brex', slug: 'brex', url: 'https://www.brex.com', description: 'Corporate card and spend management', statusPageUrl: 'https://status.brex.com' },
      { name: 'Mercury', slug: 'mercury', url: 'https://mercury.com', description: 'Banking for startups and tech companies', statusPageUrl: null },
      { name: 'SoFi', slug: 'sofi', url: 'https://www.sofi.com', description: 'Online personal finance company', statusPageUrl: null },
      { name: 'Ally Bank', slug: 'ally-bank', url: 'https://www.ally.com', description: 'Online-only bank and financial services', statusPageUrl: null },
      { name: 'Marcus by Goldman Sachs', slug: 'marcus-goldman-sachs', url: 'https://www.marcus.com', description: 'Goldman Sachs online consumer banking', statusPageUrl: null },
      { name: 'US Bank', slug: 'us-bank', url: 'https://www.usbank.com', description: 'American banking and financial services', statusPageUrl: null },
      { name: 'PNC Bank', slug: 'pnc-bank', url: 'https://www.pnc.com', description: 'American financial services corporation', statusPageUrl: null },
      { name: 'TD Bank', slug: 'td-bank', url: 'https://www.td.com', description: 'Toronto-Dominion banking group', statusPageUrl: null },
      { name: 'HSBC', slug: 'hsbc', url: 'https://www.hsbc.com', description: 'British multinational banking', statusPageUrl: null },
      { name: 'Barclays', slug: 'barclays', url: 'https://www.barclays.co.uk', description: 'British multinational bank', statusPageUrl: null },
      { name: 'Monzo', slug: 'monzo', url: 'https://monzo.com', description: 'UK digital-only bank', statusPageUrl: null },
      { name: 'N26', slug: 'n26', url: 'https://n26.com', description: 'German neobank and digital banking', statusPageUrl: null },
      { name: 'Nubank', slug: 'nubank', url: 'https://nubank.com.br', description: 'Brazilian digital banking platform', statusPageUrl: null },
      { name: 'Wealthsimple', slug: 'wealthsimple', url: 'https://www.wealthsimple.com', description: 'Canadian online investment management', statusPageUrl: null },
      { name: 'Interactive Brokers', slug: 'interactive-brokers', url: 'https://www.interactivebrokers.com', description: 'Electronic brokerage firm', statusPageUrl: null },
      { name: 'Charles Schwab', slug: 'charles-schwab', url: 'https://www.schwab.com', description: 'American brokerage and banking company', statusPageUrl: null },
      { name: 'Fidelity', slug: 'fidelity', url: 'https://www.fidelity.com', description: 'Multinational financial services corporation', statusPageUrl: null },
      { name: 'E-Trade', slug: 'e-trade', url: 'https://us.etrade.com', description: 'Electronic trading platform by Morgan Stanley', statusPageUrl: null },
      { name: 'Adyen', slug: 'adyen', url: 'https://www.adyen.com', description: 'Dutch payment company for enterprises', statusPageUrl: 'https://status.adyen.com' },
      { name: 'Braintree', slug: 'braintree', url: 'https://www.braintreepayments.com', description: 'Payment processing by PayPal', statusPageUrl: null },
      { name: 'Shopify Payments', slug: 'shopify-payments', url: 'https://www.shopify.com/payments', description: 'Shopify integrated payment processing', statusPageUrl: null },
      { name: 'Razorpay', slug: 'razorpay', url: 'https://razorpay.com', description: 'Indian payment gateway and financial services', statusPageUrl: null },
      { name: 'Dwolla', slug: 'dwolla', url: 'https://www.dwolla.com', description: 'Account-to-account payment platform', statusPageUrl: null },
      { name: 'Marqeta', slug: 'marqeta', url: 'https://www.marqeta.com', description: 'Modern card issuing platform', statusPageUrl: null },
      { name: 'Checkout.com', slug: 'checkout-com', url: 'https://www.checkout.com', description: 'Global payment processing platform', statusPageUrl: null },
      { name: 'GoCardless', slug: 'gocardless', url: 'https://gocardless.com', description: 'Bank-to-bank payment network', statusPageUrl: null },
      { name: 'Gemini', slug: 'gemini-exchange', url: 'https://www.gemini.com', description: 'Cryptocurrency exchange and custodian', statusPageUrl: null },
      { name: 'FTX Claims', slug: 'ftx-claims', url: 'https://claims.ftx.com', description: 'FTX bankruptcy claims portal', statusPageUrl: null },
      { name: 'Phantom Wallet', slug: 'phantom-wallet', url: 'https://phantom.app', description: 'Solana and multi-chain crypto wallet', statusPageUrl: null },
    ],
  },
  {
    name: 'ISP',
    slug: 'isp',
    icon: 'wifi',
    services: [
      { name: 'Comcast / Xfinity', slug: 'comcast-xfinity', url: 'https://www.xfinity.com', description: 'US cable and internet service provider', statusPageUrl: 'https://www.xfinity.com/support/status' },
      { name: 'AT&T', slug: 'att', url: 'https://www.att.com', description: 'American telecommunications company', statusPageUrl: null },
      { name: 'Verizon', slug: 'verizon', url: 'https://www.verizon.com', description: 'American telecommunications conglomerate', statusPageUrl: null },
      { name: 'T-Mobile', slug: 't-mobile', url: 'https://www.t-mobile.com', description: 'American wireless network operator', statusPageUrl: null },
      { name: 'Spectrum', slug: 'spectrum', url: 'https://www.spectrum.com', description: 'Charter Communications cable brand', statusPageUrl: null },
      { name: 'Cox Communications', slug: 'cox-communications', url: 'https://www.cox.com', description: 'American cable and ISP company', statusPageUrl: null },
      { name: 'CenturyLink / Lumen', slug: 'centurylink-lumen', url: 'https://www.lumen.com', description: 'American telecommunications company', statusPageUrl: 'https://status.lumen.com' },
      { name: 'Frontier Communications', slug: 'frontier-communications', url: 'https://frontier.com', description: 'Telecommunications company', statusPageUrl: null },
      { name: 'BT (British Telecom)', slug: 'bt-british-telecom', url: 'https://www.bt.com', description: 'British multinational telecommunications', statusPageUrl: null },
      { name: 'Virgin Media', slug: 'virgin-media', url: 'https://www.virginmedia.com', description: 'British telecom and cable company', statusPageUrl: null },
      { name: 'Sky Broadband', slug: 'sky-broadband', url: 'https://www.sky.com', description: 'British telecommunications provider', statusPageUrl: null },
      { name: 'Deutsche Telekom', slug: 'deutsche-telekom', url: 'https://www.telekom.de', description: 'German telecommunications company', statusPageUrl: null },
      { name: 'Orange', slug: 'orange', url: 'https://www.orange.com', description: 'French multinational telecommunications', statusPageUrl: null },
      { name: 'Vodafone', slug: 'vodafone', url: 'https://www.vodafone.com', description: 'British multinational telecom operator', statusPageUrl: null },
      { name: 'Telstra', slug: 'telstra', url: 'https://www.telstra.com.au', description: 'Australian telecommunications company', statusPageUrl: null },
      { name: 'Rogers', slug: 'rogers', url: 'https://www.rogers.com', description: 'Canadian communications company', statusPageUrl: null },
      { name: 'Bell Canada', slug: 'bell-canada', url: 'https://www.bell.ca', description: 'Canadian telecommunications company', statusPageUrl: null },
      { name: 'Telus', slug: 'telus', url: 'https://www.telus.com', description: 'Canadian telecommunications company', statusPageUrl: null },
      { name: 'NTT (Nippon Telegraph)', slug: 'ntt', url: 'https://www.ntt.com', description: 'Japanese telecommunications company', statusPageUrl: null },
      { name: 'SoftBank', slug: 'softbank', url: 'https://www.softbank.jp', description: 'Japanese telecommunications and internet', statusPageUrl: null },
      { name: 'SK Telecom', slug: 'sk-telecom', url: 'https://www.sktelecom.com', description: 'South Korean wireless carrier', statusPageUrl: null },
      { name: 'Singtel', slug: 'singtel', url: 'https://www.singtel.com', description: 'Singapore telecommunications company', statusPageUrl: null },
      { name: 'Jio', slug: 'jio', url: 'https://www.jio.com', description: 'Indian telecommunications service', statusPageUrl: null },
      { name: 'Airtel', slug: 'airtel', url: 'https://www.airtel.in', description: 'Indian telecommunications company', statusPageUrl: null },
      { name: 'Optus', slug: 'optus', url: 'https://www.optus.com.au', description: 'Australian telecommunications company', statusPageUrl: null },
      { name: 'Swisscom', slug: 'swisscom', url: 'https://www.swisscom.ch', description: 'Swiss telecommunications company', statusPageUrl: null },
      { name: 'Proximus', slug: 'proximus', url: 'https://www.proximus.be', description: 'Belgian telecommunications company', statusPageUrl: null },
      { name: 'KPN', slug: 'kpn', url: 'https://www.kpn.com', description: 'Dutch telecommunications provider', statusPageUrl: null },
      { name: 'Telia', slug: 'telia', url: 'https://www.teliacompany.com', description: 'Swedish multinational telecom', statusPageUrl: null },
      { name: 'Telenor', slug: 'telenor', url: 'https://www.telenor.com', description: 'Norwegian multinational telecom', statusPageUrl: null },
      { name: 'Movistar', slug: 'movistar', url: 'https://www.movistar.com', description: 'Telefonica telecommunications brand', statusPageUrl: null },
      { name: 'Claro', slug: 'claro', url: 'https://www.claro.com', description: 'Latin American telecom provider', statusPageUrl: null },
      { name: 'Ooredoo', slug: 'ooredoo', url: 'https://www.ooredoo.com', description: 'Qatari multinational telecom', statusPageUrl: null },
      { name: 'Etisalat', slug: 'etisalat', url: 'https://www.etisalat.ae', description: 'UAE telecommunications company', statusPageUrl: null },
      { name: 'MTN', slug: 'mtn', url: 'https://www.mtn.com', description: 'South African multinational telecom', statusPageUrl: null },
      { name: 'Safaricom', slug: 'safaricom', url: 'https://www.safaricom.co.ke', description: 'Kenyan telecommunications provider', statusPageUrl: null },
      { name: 'Starlink', slug: 'starlink', url: 'https://www.starlink.com', description: 'SpaceX satellite internet constellation', statusPageUrl: null },
      { name: 'HughesNet', slug: 'hughesnet', url: 'https://www.hughesnet.com', description: 'Satellite internet service provider', statusPageUrl: null },
      { name: 'Viasat', slug: 'viasat', url: 'https://www.viasat.com', description: 'Satellite communications company', statusPageUrl: null },
      { name: 'Google Fiber', slug: 'google-fiber', url: 'https://fiber.google.com', description: 'Google high-speed fiber internet', statusPageUrl: null },
      { name: 'Windstream', slug: 'windstream', url: 'https://www.windstream.com', description: 'American telecommunications provider', statusPageUrl: null },
      { name: 'Mediacom', slug: 'mediacom', url: 'https://mediacomcable.com', description: 'American cable television and internet', statusPageUrl: null },
      { name: 'Altice / Optimum', slug: 'altice-optimum', url: 'https://www.optimum.com', description: 'American cable and internet provider', statusPageUrl: null },
      { name: 'WOW (WideOpenWest)', slug: 'wow-wideopenwest', url: 'https://www.wowway.com', description: 'American cable and internet provider', statusPageUrl: null },
      { name: 'Consolidated Communications', slug: 'consolidated-communications', url: 'https://www.consolidated.com', description: 'American broadband and telecom', statusPageUrl: null },
      { name: 'TalkTalk', slug: 'talktalk', url: 'https://www.talktalk.co.uk', description: 'British broadband and telecom provider', statusPageUrl: null },
      { name: 'Plusnet', slug: 'plusnet', url: 'https://www.plus.net', description: 'UK internet service provider', statusPageUrl: null },
      { name: 'EE', slug: 'ee', url: 'https://ee.co.uk', description: 'British mobile network operator', statusPageUrl: null },
      { name: 'Three (3)', slug: 'three-mobile', url: 'https://www.three.co.uk', description: 'British telecommunications and internet', statusPageUrl: null },
      { name: 'Bouygues Telecom', slug: 'bouygues-telecom', url: 'https://www.bouyguestelecom.fr', description: 'French mobile phone and ISP', statusPageUrl: null },
      { name: 'Free (Iliad)', slug: 'free-iliad', url: 'https://www.free.fr', description: 'French telecom and internet provider', statusPageUrl: null },
      { name: 'SFR', slug: 'sfr', url: 'https://www.sfr.fr', description: 'French telecommunications company', statusPageUrl: null },
      { name: 'O2', slug: 'o2', url: 'https://www.o2.co.uk', description: 'British telecom provider by Telefonica', statusPageUrl: null },
      { name: 'TIM (Telecom Italia)', slug: 'tim-telecom-italia', url: 'https://www.tim.it', description: 'Italian telecommunications company', statusPageUrl: null },
      { name: 'Ziggo', slug: 'ziggo', url: 'https://www.ziggo.nl', description: 'Dutch cable operator', statusPageUrl: null },
      { name: 'Salt', slug: 'salt', url: 'https://www.salt.ch', description: 'Swiss mobile telecommunications', statusPageUrl: null },
      { name: 'A1 Telekom', slug: 'a1-telekom', url: 'https://www.a1.net', description: 'Austrian telecommunications company', statusPageUrl: null },
      { name: 'Magenta Telekom', slug: 'magenta-telekom', url: 'https://www.magenta.at', description: 'Austrian T-Mobile brand', statusPageUrl: null },
      { name: 'DNA', slug: 'dna-finland', url: 'https://www.dna.fi', description: 'Finnish telecom operator', statusPageUrl: null },
      { name: 'Elisa', slug: 'elisa', url: 'https://elisa.fi', description: 'Finnish telecom and digital services', statusPageUrl: null },
    ],
  },
  {
    name: 'Email',
    slug: 'email',
    icon: 'mail',
    services: [
      { name: 'Gmail', slug: 'gmail', url: 'https://mail.google.com', description: 'Google free email service', statusPageUrl: 'https://www.google.com/appsstatus/dashboard' },
      { name: 'Outlook', slug: 'outlook', url: 'https://outlook.live.com', description: 'Microsoft email and calendar service', statusPageUrl: 'https://portal.office.com/servicestatus' },
      { name: 'Yahoo Mail', slug: 'yahoo-mail', url: 'https://mail.yahoo.com', description: 'Yahoo free email service', statusPageUrl: null },
      { name: 'ProtonMail', slug: 'protonmail', url: 'https://proton.me/mail', description: 'End-to-end encrypted email service', statusPageUrl: 'https://status.proton.me' },
      { name: 'iCloud Mail', slug: 'icloud-mail', url: 'https://www.icloud.com/mail', description: 'Apple cloud-based email service', statusPageUrl: 'https://www.apple.com/support/systemstatus' },
      { name: 'Fastmail', slug: 'fastmail', url: 'https://www.fastmail.com', description: 'Australian email hosting service', statusPageUrl: 'https://fastmailstatus.com' },
      { name: 'Zoho Mail', slug: 'zoho-mail', url: 'https://www.zoho.com/mail', description: 'Zoho business email service', statusPageUrl: 'https://status.zoho.com' },
      { name: 'Tutanota', slug: 'tutanota', url: 'https://tutanota.com', description: 'German end-to-end encrypted email', statusPageUrl: null },
      { name: 'AOL Mail', slug: 'aol-mail', url: 'https://mail.aol.com', description: 'AOL web-based email service', statusPageUrl: null },
      { name: 'GMX Mail', slug: 'gmx-mail', url: 'https://www.gmx.com', description: 'German free email provider', statusPageUrl: null },
      { name: 'Mail.com', slug: 'mail-com', url: 'https://www.mail.com', description: 'Free email service with custom domains', statusPageUrl: null },
      { name: 'Mailfence', slug: 'mailfence', url: 'https://mailfence.com', description: 'Belgian secure email service', statusPageUrl: null },
      { name: 'Mailbox.org', slug: 'mailbox-org', url: 'https://mailbox.org', description: 'German privacy-focused email provider', statusPageUrl: null },
      { name: 'Hey.com', slug: 'hey-com', url: 'https://hey.com', description: 'Email service by Basecamp', statusPageUrl: null },
      { name: 'Posteo', slug: 'posteo', url: 'https://posteo.de', description: 'German green email provider', statusPageUrl: null },
      { name: 'Runbox', slug: 'runbox', url: 'https://runbox.com', description: 'Norwegian email hosting service', statusPageUrl: null },
      { name: 'Yandex Mail', slug: 'yandex-mail', url: 'https://mail.yandex.com', description: 'Russian free email service', statusPageUrl: null },
      { name: 'Mailchimp', slug: 'mailchimp', url: 'https://mailchimp.com', description: 'Email marketing and automation platform', statusPageUrl: 'https://status.mailchimp.com' },
      { name: 'Resend', slug: 'resend', url: 'https://resend.com', description: 'Email API for developers', statusPageUrl: null },
      { name: 'Postmark', slug: 'postmark', url: 'https://postmarkapp.com', description: 'Transactional email service for developers', statusPageUrl: 'https://status.postmarkapp.com' },
    ],
  },
  {
    name: 'Productivity',
    slug: 'productivity',
    icon: 'briefcase',
    services: [
      { name: 'Slack', slug: 'slack', url: 'https://slack.com', description: 'Business communication and messaging platform', statusPageUrl: 'https://status.slack.com' },
      { name: 'Zoom', slug: 'zoom', url: 'https://zoom.us', description: 'Video conferencing and online meetings', statusPageUrl: 'https://status.zoom.us' },
      { name: 'Microsoft Teams', slug: 'microsoft-teams', url: 'https://www.microsoft.com/en-us/microsoft-teams', description: 'Microsoft business collaboration platform', statusPageUrl: 'https://portal.office.com/servicestatus' },
      { name: 'Notion', slug: 'notion', url: 'https://www.notion.so', description: 'All-in-one workspace for notes and docs', statusPageUrl: 'https://status.notion.so' },
      { name: 'Figma', slug: 'figma', url: 'https://www.figma.com', description: 'Collaborative interface design tool', statusPageUrl: 'https://status.figma.com' },
      { name: 'GitHub', slug: 'github', url: 'https://github.com', description: 'Code hosting and collaboration platform', statusPageUrl: 'https://www.githubstatus.com' },
      { name: 'GitLab', slug: 'gitlab', url: 'https://gitlab.com', description: 'DevOps lifecycle tool and Git repository', statusPageUrl: 'https://status.gitlab.com' },
      { name: 'Jira', slug: 'jira', url: 'https://www.atlassian.com/software/jira', description: 'Issue tracking and project management', statusPageUrl: 'https://status.atlassian.com' },
      { name: 'Confluence', slug: 'confluence', url: 'https://www.atlassian.com/software/confluence', description: 'Team workspace and knowledge management', statusPageUrl: 'https://status.atlassian.com' },
      { name: 'Asana', slug: 'asana', url: 'https://asana.com', description: 'Work management and project tracking', statusPageUrl: 'https://status.asana.com' },
      { name: 'Trello', slug: 'trello', url: 'https://trello.com', description: 'Kanban-style project management', statusPageUrl: 'https://trello.status.atlassian.com' },
      { name: 'Linear', slug: 'linear', url: 'https://linear.app', description: 'Issue tracking for software teams', statusPageUrl: 'https://status.linear.app' },
      { name: 'Docker Hub', slug: 'docker-hub', url: 'https://hub.docker.com', description: 'Container image registry and repository', statusPageUrl: 'https://www.dockerstatus.com' },
      { name: 'npm', slug: 'npm', url: 'https://www.npmjs.com', description: 'JavaScript package manager registry', statusPageUrl: 'https://status.npmjs.org' },
      { name: 'Google Workspace', slug: 'google-workspace', url: 'https://workspace.google.com', description: 'Google collaboration and productivity suite', statusPageUrl: 'https://www.google.com/appsstatus/dashboard' },
      { name: 'Microsoft 365', slug: 'microsoft-365', url: 'https://www.microsoft.com/en-us/microsoft-365', description: 'Microsoft productivity and cloud suite', statusPageUrl: 'https://portal.office.com/servicestatus' },
      { name: 'Dropbox', slug: 'dropbox', url: 'https://www.dropbox.com', description: 'File hosting and cloud storage service', statusPageUrl: 'https://status.dropbox.com' },
      { name: 'Google Drive', slug: 'google-drive', url: 'https://drive.google.com', description: 'Google cloud file storage and sync', statusPageUrl: 'https://www.google.com/appsstatus/dashboard' },
      { name: 'OneDrive', slug: 'onedrive', url: 'https://www.microsoft.com/en-us/microsoft-365/onedrive', description: 'Microsoft cloud storage service', statusPageUrl: null },
      { name: 'Box', slug: 'box', url: 'https://www.box.com', description: 'Cloud content management and file sharing', statusPageUrl: 'https://status.box.com' },
      { name: 'Airtable', slug: 'airtable', url: 'https://www.airtable.com', description: 'Cloud collaboration and spreadsheet-database', statusPageUrl: 'https://status.airtable.com' },
      { name: 'Monday.com', slug: 'monday-com', url: 'https://monday.com', description: 'Work operating system for teams', statusPageUrl: 'https://status.monday.com' },
      { name: 'ClickUp', slug: 'clickup', url: 'https://clickup.com', description: 'All-in-one productivity and project management', statusPageUrl: 'https://clickup.statuspage.io' },
      { name: 'Miro', slug: 'miro', url: 'https://miro.com', description: 'Online collaborative whiteboard platform', statusPageUrl: 'https://status.miro.com' },
      { name: 'Canva', slug: 'canva', url: 'https://www.canva.com', description: 'Online graphic design platform', statusPageUrl: null },
      { name: 'Loom', slug: 'loom', url: 'https://www.loom.com', description: 'Video messaging and screen recording', statusPageUrl: null },
      { name: 'Calendly', slug: 'calendly', url: 'https://calendly.com', description: 'Online appointment scheduling', statusPageUrl: 'https://status.calendly.com' },
      { name: 'Intercom', slug: 'intercom', url: 'https://www.intercom.com', description: 'Customer messaging and support platform', statusPageUrl: 'https://status.intercom.com' },
      { name: 'Zendesk', slug: 'zendesk', url: 'https://www.zendesk.com', description: 'Customer service and engagement platform', statusPageUrl: 'https://status.zendesk.com' },
      { name: 'HubSpot', slug: 'hubspot', url: 'https://www.hubspot.com', description: 'CRM and inbound marketing platform', statusPageUrl: 'https://status.hubspot.com' },
      { name: 'Salesforce', slug: 'salesforce', url: 'https://www.salesforce.com', description: 'Cloud-based CRM platform', statusPageUrl: 'https://status.salesforce.com' },
      { name: 'Vercel Dashboard', slug: 'vercel-dashboard', url: 'https://vercel.com/dashboard', description: 'Vercel deployment management dashboard', statusPageUrl: 'https://www.vercel-status.com' },
      { name: 'CircleCI', slug: 'circleci', url: 'https://circleci.com', description: 'Continuous integration and delivery platform', statusPageUrl: 'https://status.circleci.com' },
      { name: 'GitHub Actions', slug: 'github-actions', url: 'https://github.com/features/actions', description: 'GitHub CI/CD workflow automation', statusPageUrl: 'https://www.githubstatus.com' },
      { name: 'Bitbucket', slug: 'bitbucket', url: 'https://bitbucket.org', description: 'Atlassian Git-based code hosting', statusPageUrl: 'https://status.atlassian.com' },
      { name: 'Webex', slug: 'webex', url: 'https://www.webex.com', description: 'Cisco video conferencing platform', statusPageUrl: 'https://status.webex.com' },
      { name: 'Google Meet', slug: 'google-meet', url: 'https://meet.google.com', description: 'Google video conferencing service', statusPageUrl: 'https://www.google.com/appsstatus/dashboard' },
      { name: 'Coda', slug: 'coda', url: 'https://coda.io', description: 'Document and workflow automation platform', statusPageUrl: null },
      { name: 'Obsidian Sync', slug: 'obsidian-sync', url: 'https://obsidian.md', description: 'Obsidian note sync and publish service', statusPageUrl: null },
      { name: 'Todoist', slug: 'todoist', url: 'https://todoist.com', description: 'Task management and to-do list app', statusPageUrl: null },
    ],
  },
  {
    name: 'E-commerce',
    slug: 'ecommerce',
    icon: 'shopping-cart',
    services: [
      { name: 'Amazon', slug: 'amazon', url: 'https://www.amazon.com', description: 'Global online marketplace and retailer', statusPageUrl: null },
      { name: 'Shopify', slug: 'shopify', url: 'https://www.shopify.com', description: 'E-commerce platform for online stores', statusPageUrl: 'https://www.shopifystatus.com' },
      { name: 'eBay', slug: 'ebay', url: 'https://www.ebay.com', description: 'Online auction and shopping website', statusPageUrl: null },
      { name: 'Walmart', slug: 'walmart', url: 'https://www.walmart.com', description: 'American multinational retail corporation', statusPageUrl: null },
      { name: 'Target', slug: 'target', url: 'https://www.target.com', description: 'American retail corporation', statusPageUrl: null },
      { name: 'Etsy', slug: 'etsy', url: 'https://www.etsy.com', description: 'Marketplace for handmade and vintage items', statusPageUrl: null },
      { name: 'AliExpress', slug: 'aliexpress', url: 'https://www.aliexpress.com', description: 'Chinese online retail service by Alibaba', statusPageUrl: null },
      { name: 'Best Buy', slug: 'best-buy', url: 'https://www.bestbuy.com', description: 'American consumer electronics retailer', statusPageUrl: null },
      { name: 'Wayfair', slug: 'wayfair', url: 'https://www.wayfair.com', description: 'American e-commerce for home goods', statusPageUrl: null },
      { name: 'Costco', slug: 'costco', url: 'https://www.costco.com', description: 'American warehouse club retailer', statusPageUrl: null },
      { name: 'Home Depot', slug: 'home-depot', url: 'https://www.homedepot.com', description: 'American home improvement retailer', statusPageUrl: null },
      { name: "Lowe's", slug: 'lowes', url: 'https://www.lowes.com', description: 'American home improvement retailer', statusPageUrl: null },
      { name: 'Instacart', slug: 'instacart', url: 'https://www.instacart.com', description: 'Grocery delivery and pickup service', statusPageUrl: null },
      { name: 'DoorDash', slug: 'doordash', url: 'https://www.doordash.com', description: 'Food delivery platform', statusPageUrl: null },
      { name: 'Uber Eats', slug: 'uber-eats', url: 'https://www.ubereats.com', description: 'Uber food delivery service', statusPageUrl: null },
      { name: 'Grubhub', slug: 'grubhub', url: 'https://www.grubhub.com', description: 'Online food ordering and delivery', statusPageUrl: null },
      { name: 'Nike', slug: 'nike', url: 'https://www.nike.com', description: 'Nike online store and app', statusPageUrl: null },
      { name: 'Zara', slug: 'zara', url: 'https://www.zara.com', description: 'Spanish fast fashion retailer', statusPageUrl: null },
      { name: 'ASOS', slug: 'asos', url: 'https://www.asos.com', description: 'British online fashion retailer', statusPageUrl: null },
      { name: 'Wish', slug: 'wish', url: 'https://www.wish.com', description: 'American online e-commerce platform', statusPageUrl: null },
      { name: 'Mercado Libre', slug: 'mercado-libre', url: 'https://www.mercadolibre.com', description: 'Latin American e-commerce platform', statusPageUrl: null },
      { name: 'Flipkart', slug: 'flipkart', url: 'https://www.flipkart.com', description: 'Indian e-commerce company', statusPageUrl: null },
      { name: 'Rakuten', slug: 'rakuten', url: 'https://www.rakuten.com', description: 'Japanese electronic commerce company', statusPageUrl: null },
      { name: 'Zalando', slug: 'zalando', url: 'https://www.zalando.com', description: 'European online fashion platform', statusPageUrl: null },
      { name: 'BigCommerce', slug: 'bigcommerce', url: 'https://www.bigcommerce.com', description: 'E-commerce platform for online stores', statusPageUrl: 'https://status.bigcommerce.com' },
      { name: 'WooCommerce', slug: 'woocommerce', url: 'https://woocommerce.com', description: 'Open-source WordPress e-commerce plugin', statusPageUrl: null },
      { name: 'Squarespace', slug: 'squarespace', url: 'https://www.squarespace.com', description: 'Website builder and e-commerce platform', statusPageUrl: 'https://status.squarespace.com' },
      { name: 'Wix', slug: 'wix', url: 'https://www.wix.com', description: 'Website builder and hosting platform', statusPageUrl: 'https://www.wixstatus.com' },
      { name: 'Chewy', slug: 'chewy', url: 'https://www.chewy.com', description: 'Online pet food and product retailer', statusPageUrl: null },
      { name: 'Temu', slug: 'temu', url: 'https://www.temu.com', description: 'Chinese-owned online marketplace', statusPageUrl: null },
    ],
  },
  {
    name: 'Other',
    slug: 'other',
    icon: 'globe',
    services: [
      { name: 'OpenAI', slug: 'openai', url: 'https://openai.com', description: 'AI research and deployment company', statusPageUrl: 'https://status.openai.com' },
      { name: 'ChatGPT', slug: 'chatgpt', url: 'https://chat.openai.com', description: 'AI conversational assistant by OpenAI', statusPageUrl: 'https://status.openai.com' },
      { name: 'Claude (Anthropic)', slug: 'claude-anthropic', url: 'https://claude.ai', description: 'AI assistant by Anthropic', statusPageUrl: 'https://status.anthropic.com' },
      { name: 'Google Gemini', slug: 'google-gemini', url: 'https://gemini.google.com', description: 'Google multimodal AI model', statusPageUrl: null },
      { name: 'Perplexity', slug: 'perplexity', url: 'https://www.perplexity.ai', description: 'AI-powered search engine', statusPageUrl: null },
      { name: 'Midjourney', slug: 'midjourney', url: 'https://www.midjourney.com', description: 'AI image generation service', statusPageUrl: null },
      { name: 'Stability AI', slug: 'stability-ai', url: 'https://stability.ai', description: 'Open-source AI image generation', statusPageUrl: null },
      { name: 'Hugging Face', slug: 'hugging-face', url: 'https://huggingface.co', description: 'AI model hosting and machine learning platform', statusPageUrl: null },
      { name: 'Replicate', slug: 'replicate', url: 'https://replicate.com', description: 'Run ML models in the cloud', statusPageUrl: null },
      { name: 'Uber', slug: 'uber', url: 'https://www.uber.com', description: 'Ride-hailing and mobility platform', statusPageUrl: null },
      { name: 'Lyft', slug: 'lyft', url: 'https://www.lyft.com', description: 'Ride-sharing transportation network', statusPageUrl: null },
      { name: 'Airbnb', slug: 'airbnb', url: 'https://www.airbnb.com', description: 'Online marketplace for lodging and tourism', statusPageUrl: null },
      { name: 'Booking.com', slug: 'booking-com', url: 'https://www.booking.com', description: 'Online travel agency for lodging', statusPageUrl: null },
      { name: 'Expedia', slug: 'expedia', url: 'https://www.expedia.com', description: 'Online travel shopping company', statusPageUrl: null },
      { name: 'Google Maps', slug: 'google-maps', url: 'https://maps.google.com', description: 'Google web mapping service', statusPageUrl: null },
      { name: 'Apple Maps', slug: 'apple-maps', url: 'https://maps.apple.com', description: 'Apple web mapping service', statusPageUrl: null },
      { name: 'Waze', slug: 'waze', url: 'https://www.waze.com', description: 'Community-driven GPS navigation app', statusPageUrl: null },
      { name: 'Google Search', slug: 'google-search', url: 'https://www.google.com', description: 'Google web search engine', statusPageUrl: null },
      { name: 'Bing', slug: 'bing', url: 'https://www.bing.com', description: 'Microsoft web search engine', statusPageUrl: null },
      { name: 'DuckDuckGo', slug: 'duckduckgo', url: 'https://duckduckgo.com', description: 'Privacy-focused search engine', statusPageUrl: null },
      { name: 'Wikipedia', slug: 'wikipedia', url: 'https://www.wikipedia.org', description: 'Free online encyclopedia', statusPageUrl: null },
      { name: 'Archive.org', slug: 'archive-org', url: 'https://archive.org', description: 'Internet Archive digital library', statusPageUrl: null },
      { name: 'Cloudflare DNS', slug: 'cloudflare-dns', url: 'https://1.1.1.1', description: 'Cloudflare public DNS resolver', statusPageUrl: 'https://www.cloudflarestatus.com' },
      { name: 'Google DNS', slug: 'google-dns', url: 'https://dns.google', description: 'Google public DNS resolver', statusPageUrl: null },
      { name: 'Quad9', slug: 'quad9', url: 'https://quad9.net', description: 'Free public DNS security platform', statusPageUrl: null },
      { name: 'OpenDNS', slug: 'opendns', url: 'https://www.opendns.com', description: 'Cisco DNS-based web filtering', statusPageUrl: null },
      { name: "Let's Encrypt", slug: 'lets-encrypt', url: 'https://letsencrypt.org', description: 'Free TLS certificate authority', statusPageUrl: 'https://letsencrypt.status.io' },
      { name: 'Auth0', slug: 'auth0', url: 'https://auth0.com', description: 'Identity and access management platform', statusPageUrl: 'https://status.auth0.com' },
      { name: 'Okta', slug: 'okta', url: 'https://www.okta.com', description: 'Identity and access management company', statusPageUrl: 'https://status.okta.com' },
      { name: 'Firebase', slug: 'firebase', url: 'https://firebase.google.com', description: 'Google app development platform', statusPageUrl: 'https://status.firebase.google.com' },
      { name: 'Algolia', slug: 'algolia', url: 'https://www.algolia.com', description: 'Search-as-a-service platform', statusPageUrl: 'https://status.algolia.com' },
      { name: 'Contentful', slug: 'contentful', url: 'https://www.contentful.com', description: 'Headless content management system', statusPageUrl: 'https://www.contentfulstatus.com' },
      { name: 'Sanity', slug: 'sanity', url: 'https://www.sanity.io', description: 'Composable content platform', statusPageUrl: null },
      { name: 'Strapi', slug: 'strapi', url: 'https://strapi.io', description: 'Open-source headless CMS', statusPageUrl: null },
      { name: 'WordPress.com', slug: 'wordpress-com', url: 'https://wordpress.com', description: 'Blog hosting and website builder', statusPageUrl: 'https://www.automatticstatus.com' },
      { name: 'Medium', slug: 'medium', url: 'https://medium.com', description: 'Online publishing platform', statusPageUrl: null },
      { name: 'Substack', slug: 'substack', url: 'https://substack.com', description: 'Newsletter publishing platform', statusPageUrl: null },
      { name: 'Ghost', slug: 'ghost', url: 'https://ghost.org', description: 'Open-source publishing platform', statusPageUrl: null },
      { name: 'Cloudflare Pages', slug: 'cloudflare-pages', url: 'https://pages.cloudflare.com', description: 'JAMstack platform by Cloudflare', statusPageUrl: 'https://www.cloudflarestatus.com' },
      { name: 'Vercel Edge', slug: 'vercel-edge', url: 'https://vercel.com/features/edge-functions', description: 'Vercel edge function runtime', statusPageUrl: 'https://www.vercel-status.com' },
      { name: 'Mapbox', slug: 'mapbox', url: 'https://www.mapbox.com', description: 'Maps and location data platform', statusPageUrl: 'https://status.mapbox.com' },
      { name: 'Segment', slug: 'segment', url: 'https://segment.com', description: 'Customer data platform', statusPageUrl: 'https://status.segment.com' },
      { name: 'Amplitude', slug: 'amplitude', url: 'https://amplitude.com', description: 'Digital analytics platform', statusPageUrl: 'https://status.amplitude.com' },
      { name: 'Mixpanel', slug: 'mixpanel', url: 'https://mixpanel.com', description: 'Product analytics platform', statusPageUrl: 'https://status.mixpanel.com' },
      { name: 'Google Analytics', slug: 'google-analytics', url: 'https://analytics.google.com', description: 'Google web analytics service', statusPageUrl: null },
      { name: 'Hotjar', slug: 'hotjar', url: 'https://www.hotjar.com', description: 'Website heatmaps and behavior analytics', statusPageUrl: null },
      { name: 'Vercel AI SDK', slug: 'vercel-ai-sdk', url: 'https://sdk.vercel.ai', description: 'Vercel AI development toolkit', statusPageUrl: null },
      { name: 'Cursor', slug: 'cursor', url: 'https://cursor.sh', description: 'AI-powered code editor', statusPageUrl: null },
      { name: 'Replit', slug: 'replit', url: 'https://replit.com', description: 'Online IDE and coding platform', statusPageUrl: null },
      { name: 'CodeSandbox', slug: 'codesandbox', url: 'https://codesandbox.io', description: 'Online code editor and prototyping', statusPageUrl: null },
      { name: 'StackBlitz', slug: 'stackblitz', url: 'https://stackblitz.com', description: 'Online IDE for web development', statusPageUrl: null },
      { name: 'Codepen', slug: 'codepen', url: 'https://codepen.io', description: 'Social development environment for front-end', statusPageUrl: null },
      { name: 'JSFiddle', slug: 'jsfiddle', url: 'https://jsfiddle.net', description: 'Online JavaScript code editor', statusPageUrl: null },
      { name: 'Stack Overflow', slug: 'stack-overflow', url: 'https://stackoverflow.com', description: 'Q&A platform for developers', statusPageUrl: null },
      { name: 'npm Registry', slug: 'npm-registry', url: 'https://registry.npmjs.org', description: 'npm package registry infrastructure', statusPageUrl: 'https://status.npmjs.org' },
      { name: 'PyPI', slug: 'pypi', url: 'https://pypi.org', description: 'Python Package Index', statusPageUrl: 'https://status.python.org' },
      { name: 'crates.io', slug: 'crates-io', url: 'https://crates.io', description: 'Rust package registry', statusPageUrl: null },
      { name: 'Maven Central', slug: 'maven-central', url: 'https://central.sonatype.com', description: 'Java package repository', statusPageUrl: null },
      { name: 'NuGet', slug: 'nuget', url: 'https://www.nuget.org', description: '.NET package manager', statusPageUrl: null },
      { name: 'RubyGems', slug: 'rubygems', url: 'https://rubygems.org', description: 'Ruby community gem hosting', statusPageUrl: null },
      { name: 'Packagist', slug: 'packagist', url: 'https://packagist.org', description: 'PHP package repository', statusPageUrl: null },
      { name: 'CocoaPods', slug: 'cocoapods', url: 'https://cocoapods.org', description: 'iOS/macOS dependency manager', statusPageUrl: null },
      { name: 'Google Play Store', slug: 'google-play-store', url: 'https://play.google.com', description: 'Google Android app distribution', statusPageUrl: null },
      { name: 'Apple App Store', slug: 'apple-app-store', url: 'https://www.apple.com/app-store', description: 'Apple iOS app distribution', statusPageUrl: 'https://www.apple.com/support/systemstatus' },
      { name: 'iCloud', slug: 'icloud', url: 'https://www.icloud.com', description: 'Apple cloud storage and sync services', statusPageUrl: 'https://www.apple.com/support/systemstatus' },
      { name: 'Google Photos', slug: 'google-photos', url: 'https://photos.google.com', description: 'Google photo storage and sharing', statusPageUrl: null },
      { name: 'Flickr', slug: 'flickr', url: 'https://www.flickr.com', description: 'Image and video hosting service', statusPageUrl: null },
      { name: 'Imgur', slug: 'imgur', url: 'https://imgur.com', description: 'Image sharing community', statusPageUrl: null },
      { name: 'Giphy', slug: 'giphy', url: 'https://giphy.com', description: 'GIF search engine and sharing', statusPageUrl: null },
      { name: '1Password', slug: '1password', url: 'https://1password.com', description: 'Password manager and digital vault', statusPageUrl: 'https://1password.statuspage.io' },
      { name: 'LastPass', slug: 'lastpass', url: 'https://www.lastpass.com', description: 'Password management service', statusPageUrl: 'https://status.lastpass.com' },
      { name: 'Bitwarden', slug: 'bitwarden', url: 'https://bitwarden.com', description: 'Open-source password manager', statusPageUrl: 'https://status.bitwarden.com' },
      { name: 'NordVPN', slug: 'nordvpn', url: 'https://nordvpn.com', description: 'Virtual private network service', statusPageUrl: null },
      { name: 'ExpressVPN', slug: 'expressvpn', url: 'https://www.expressvpn.com', description: 'VPN service provider', statusPageUrl: null },
      { name: 'Mullvad VPN', slug: 'mullvad-vpn', url: 'https://mullvad.net', description: 'Privacy-focused VPN service', statusPageUrl: null },
      { name: 'Tailscale', slug: 'tailscale', url: 'https://tailscale.com', description: 'WireGuard-based mesh VPN service', statusPageUrl: 'https://status.tailscale.com' },
      { name: 'Cloudflare WARP', slug: 'cloudflare-warp', url: 'https://1.1.1.1', description: 'Cloudflare consumer VPN and DNS', statusPageUrl: 'https://www.cloudflarestatus.com' },
      { name: 'FedEx', slug: 'fedex', url: 'https://www.fedex.com', description: 'Package delivery and logistics', statusPageUrl: null },
      { name: 'UPS', slug: 'ups', url: 'https://www.ups.com', description: 'Package delivery and supply chain', statusPageUrl: null },
      { name: 'USPS', slug: 'usps', url: 'https://www.usps.com', description: 'United States Postal Service', statusPageUrl: null },
      { name: 'DHL', slug: 'dhl', url: 'https://www.dhl.com', description: 'International courier and logistics', statusPageUrl: null },
      { name: 'Twitch Drops', slug: 'twitch-drops', url: 'https://www.twitch.tv/drops', description: 'Twitch in-game reward distribution', statusPageUrl: null },
      { name: 'Zapier', slug: 'zapier', url: 'https://zapier.com', description: 'Workflow automation platform', statusPageUrl: 'https://status.zapier.com' },
      { name: 'IFTTT', slug: 'ifttt', url: 'https://ifttt.com', description: 'Web-based automation service', statusPageUrl: null },
      { name: 'Make (Integromat)', slug: 'make-integromat', url: 'https://www.make.com', description: 'Visual automation platform', statusPageUrl: 'https://status.make.com' },
      { name: 'Webflow', slug: 'webflow', url: 'https://webflow.com', description: 'Visual web design and development platform', statusPageUrl: 'https://status.webflow.com' },
      { name: 'Framer', slug: 'framer', url: 'https://www.framer.com', description: 'Interactive design and website builder', statusPageUrl: null },
      { name: 'Sumo Logic', slug: 'sumo-logic', url: 'https://www.sumologic.com', description: 'Cloud-native machine data analytics', statusPageUrl: 'https://status.sumologic.com' },
      { name: 'Splunk', slug: 'splunk', url: 'https://www.splunk.com', description: 'Data analytics and security platform', statusPageUrl: null },
      { name: 'Vercel Analytics', slug: 'vercel-analytics', url: 'https://vercel.com/analytics', description: 'Vercel web analytics service', statusPageUrl: null },
      { name: 'Statuspage (Atlassian)', slug: 'statuspage-atlassian', url: 'https://www.atlassian.com/software/statuspage', description: 'Status and incident communication', statusPageUrl: 'https://metastatuspage.com' },
      { name: 'Better Stack', slug: 'better-stack', url: 'https://betterstack.com', description: 'Observability and incident management', statusPageUrl: null },
      { name: 'OpsGenie', slug: 'opsgenie', url: 'https://www.atlassian.com/software/opsgenie', description: 'Incident management by Atlassian', statusPageUrl: 'https://status.atlassian.com' },
      { name: 'VictorOps (Splunk On-Call)', slug: 'victorops-splunk-on-call', url: 'https://www.splunk.com/en_us/products/on-call.html', description: 'Incident management platform', statusPageUrl: null },
      { name: 'Grafana', slug: 'grafana', url: 'https://grafana.com', description: 'Open-source analytics and monitoring', statusPageUrl: 'https://status.grafana.com' },
      { name: 'Prometheus', slug: 'prometheus', url: 'https://prometheus.io', description: 'Open-source systems monitoring toolkit', statusPageUrl: null },
      { name: 'Wayback Machine', slug: 'wayback-machine', url: 'https://web.archive.org', description: 'Internet Archive web page time machine', statusPageUrl: null },
      { name: 'OpenAI API', slug: 'openai-api', url: 'https://api.openai.com', description: 'OpenAI developer API service', statusPageUrl: 'https://status.openai.com' },
      { name: 'Anthropic API', slug: 'anthropic-api', url: 'https://api.anthropic.com', description: 'Anthropic developer API service', statusPageUrl: 'https://status.anthropic.com' },
      { name: 'Cohere', slug: 'cohere', url: 'https://cohere.com', description: 'Enterprise AI platform', statusPageUrl: null },
      { name: 'Together AI', slug: 'together-ai', url: 'https://www.together.ai', description: 'Open-source AI model hosting', statusPageUrl: null },
      { name: 'Groq', slug: 'groq', url: 'https://groq.com', description: 'AI inference acceleration platform', statusPageUrl: null },
      { name: 'DeepL', slug: 'deepl', url: 'https://www.deepl.com', description: 'AI-powered language translation', statusPageUrl: null },
      { name: 'Grammarly', slug: 'grammarly', url: 'https://www.grammarly.com', description: 'AI writing assistant platform', statusPageUrl: null },
      { name: 'Notion AI', slug: 'notion-ai', url: 'https://www.notion.so/product/ai', description: 'Notion integrated AI assistant', statusPageUrl: 'https://status.notion.so' },
      { name: 'Jasper AI', slug: 'jasper-ai', url: 'https://www.jasper.ai', description: 'AI content creation platform', statusPageUrl: null },
      { name: 'RunwayML', slug: 'runwayml', url: 'https://runwayml.com', description: 'AI video and creative generation', statusPageUrl: null },
      { name: 'ElevenLabs', slug: 'elevenlabs', url: 'https://elevenlabs.io', description: 'AI voice synthesis platform', statusPageUrl: null },
      { name: 'Suno AI', slug: 'suno-ai', url: 'https://suno.ai', description: 'AI music generation platform', statusPageUrl: null },
      { name: 'Character.AI', slug: 'character-ai', url: 'https://character.ai', description: 'AI character conversation platform', statusPageUrl: null },
      { name: 'V0 by Vercel', slug: 'v0-vercel', url: 'https://v0.dev', description: 'AI-powered UI generation tool', statusPageUrl: null },
      { name: 'Bolt.new', slug: 'bolt-new', url: 'https://bolt.new', description: 'AI-powered full-stack app builder', statusPageUrl: null },
      { name: 'Retool', slug: 'retool', url: 'https://retool.com', description: 'Low-code platform for internal tools', statusPageUrl: 'https://status.retool.com' },
      { name: 'Vercel Blob', slug: 'vercel-blob', url: 'https://vercel.com/docs/storage/vercel-blob', description: 'Vercel serverless file storage', statusPageUrl: 'https://www.vercel-status.com' },
      { name: 'Render Cron Jobs', slug: 'render-cron-jobs', url: 'https://render.com/docs/cronjobs', description: 'Render managed cron job service', statusPageUrl: 'https://status.render.com' },
      { name: 'Durable Objects (Cloudflare)', slug: 'cloudflare-durable-objects', url: 'https://developers.cloudflare.com/durable-objects', description: 'Cloudflare stateful serverless compute', statusPageUrl: 'https://www.cloudflarestatus.com' },
      { name: 'Uptime Robot', slug: 'uptime-robot', url: 'https://uptimerobot.com', description: 'Website uptime monitoring service', statusPageUrl: null },
      { name: 'Pingdom', slug: 'pingdom', url: 'https://www.pingdom.com', description: 'Website performance and availability monitoring', statusPageUrl: null },
      { name: 'StatusCake', slug: 'statuscake', url: 'https://www.statuscake.com', description: 'Website monitoring and alerting', statusPageUrl: null },
      { name: 'Freshdesk', slug: 'freshdesk', url: 'https://www.freshworks.com/freshdesk', description: 'Cloud-based customer support software', statusPageUrl: null },
    ],
  },
];

async function seed(): Promise<void> {
  const sql = postgres(DATABASE_URL);

  try {
    console.log('Starting database seed...');
    console.log(`Connecting to: ${DATABASE_URL.replace(/:[^:@]+@/, ':****@')}`);

    // Insert categories
    console.log('Inserting service categories...');
    for (const cat of categories) {
      await sql`
        INSERT INTO service_categories (name, slug, icon)
        VALUES (${cat.name}, ${cat.slug}, ${cat.icon})
        ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon
      `;
    }
    console.log(`  Inserted ${categories.length} categories.`);

    // Fetch category IDs
    const catRows = await sql`SELECT id, slug FROM service_categories`;
    const catMap = new Map<string, number>();
    for (const row of catRows) {
      catMap.set(row.slug as string, row.id as number);
    }

    // Insert services
    let totalServices = 0;
    for (const cat of categories) {
      const categoryId = catMap.get(cat.slug);
      if (categoryId === undefined) {
        console.error(`  Category not found: ${cat.slug}`);
        continue;
      }

      console.log(`  Inserting ${cat.services.length} services for ${cat.name}...`);

      // Batch insert in groups of 50
      for (let i = 0; i < cat.services.length; i += 50) {
        const batch = cat.services.slice(i, i + 50);

        for (const svc of batch) {
          await sql`
            INSERT INTO services (slug, name, category_id, url, description, status_page_url)
            VALUES (${svc.slug}, ${svc.name}, ${categoryId}, ${svc.url}, ${svc.description}, ${svc.statusPageUrl})
            ON CONFLICT (slug) DO UPDATE SET
              name = EXCLUDED.name,
              category_id = EXCLUDED.category_id,
              url = EXCLUDED.url,
              description = EXCLUDED.description,
              status_page_url = EXCLUDED.status_page_url,
              updated_at = now()
          `;
        }

        totalServices += batch.length;
      }
    }

    console.log(`  Inserted ${totalServices} services total.`);
    console.log('Seed completed successfully.');
  } catch (error) {
    console.error('Seed failed:', error);
    process.exit(1);
  } finally {
    await sql.end();
  }
}

seed();
